import { type PackageBuild, preset } from "@plainworks/tsdown-config"

// Generated by `registry:codegen` from the atoms on disk — do not edit the entry map by hand.
// Each atom is its own client entry so consumers tree-shake to the atoms they import.
export const build: PackageBuild = {
  entry: {
    index: "src/index.ts",
    accordion: "src/shadcn/accordion.tsx",
    alert: "src/shadcn/alert.tsx",
    "alert-dialog": "src/shadcn/alert-dialog.tsx",
    "aspect-ratio": "src/shadcn/aspect-ratio.tsx",
    avatar: "src/shadcn/avatar.tsx",
    badge: "src/shadcn/badge.tsx",
    breadcrumb: "src/shadcn/breadcrumb.tsx",
    button: "src/shadcn/button.tsx",
    "button-group": "src/shadcn/button-group.tsx",
    calendar: "src/shadcn/calendar.tsx",
    card: "src/shadcn/card.tsx",
    checkbox: "src/shadcn/checkbox.tsx",
    collapsible: "src/shadcn/collapsible.tsx",
    command: "src/shadcn/command.tsx",
    "context-menu": "src/shadcn/context-menu.tsx",
    dialog: "src/shadcn/dialog.tsx",
    "dropdown-menu": "src/shadcn/dropdown-menu.tsx",
    empty: "src/shadcn/empty.tsx",
    field: "src/shadcn/field.tsx",
    "hover-card": "src/shadcn/hover-card.tsx",
    input: "src/shadcn/input.tsx",
    "input-group": "src/shadcn/input-group.tsx",
    "input-otp": "src/shadcn/input-otp.tsx",
    item: "src/shadcn/item.tsx",
    kbd: "src/shadcn/kbd.tsx",
    label: "src/shadcn/label.tsx",
    menubar: "src/shadcn/menubar.tsx",
    "native-select": "src/shadcn/native-select.tsx",
    "navigation-menu": "src/shadcn/navigation-menu.tsx",
    "number-field": "src/atoms/number-field.tsx",
    pagination: "src/shadcn/pagination.tsx",
    popover: "src/shadcn/popover.tsx",
    progress: "src/shadcn/progress.tsx",
    "radio-group": "src/shadcn/radio-group.tsx",
    "scroll-area": "src/shadcn/scroll-area.tsx",
    select: "src/shadcn/select.tsx",
    separator: "src/shadcn/separator.tsx",
    sheet: "src/shadcn/sheet.tsx",
    skeleton: "src/shadcn/skeleton.tsx",
    slider: "src/shadcn/slider.tsx",
    spinner: "src/shadcn/spinner.tsx",
    switch: "src/shadcn/switch.tsx",
    table: "src/shadcn/table.tsx",
    tabs: "src/shadcn/tabs.tsx",
    textarea: "src/shadcn/textarea.tsx",
    toast: "src/shadcn/toast.tsx",
    toggle: "src/shadcn/toggle.tsx",
    "toggle-group": "src/shadcn/toggle-group.tsx",
    tooltip: "src/shadcn/tooltip.tsx",
  },
  // A DOM-only package: its client components render into the browser DOM.
  dom: true,
  // tsdown has no CSS pipeline, so the Tailwind-source stylesheet is copied verbatim.
  assets: { "styles.css": { from: "src/styles.css" } },
  // The shadcn registry points at the atom sources, and the lock pins them to upstream.
  files: ["registry.json", "shadcn.lock.json"],
  // Vendored shadcn atoms carry no `isolatedDeclarations` annotations, so declarations are
  // emitted with tsc through the vendored project, and consumers read the built atoms.
  tsconfig: "tsconfig.shadcn.json",
  vendored: "src/shadcn",
}

export default preset(build)
