// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file events.proto (package plainworks.reference.v1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf"
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2"
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2"

/**
 * Describes the file events.proto.
 */
export const file_events: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CgxldmVudHMucHJvdG8SF3BsYWlud29ya3MucmVmZXJlbmNlLnYxIigKC1Rhc2tDaGFuZ2VkEgoKAmlkGAEgASgJEg0KBXRpdGxlGAIgASgJYgZwcm90bzM",
  )

/**
 * @generated from message plainworks.reference.v1.TaskChanged
 */
export type TaskChanged = Message<"plainworks.reference.v1.TaskChanged"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string

  /**
   * @generated from field: string title = 2;
   */
  title: string
}

/**
 * Describes the message plainworks.reference.v1.TaskChanged.
 * Use `create(TaskChangedSchema)` to create a new message.
 */
export const TaskChangedSchema: GenMessage<TaskChanged> = /*@__PURE__*/ messageDesc(file_events, 0)
