// @generated by protoc-gen-es v2.14.1 with parameter "target=ts,import_extension=js"
// @generated from file identity.proto (package gokit.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2"
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2"
import type { EmptySchema, StringValueSchema } from "@bufbuild/protobuf/wkt"
import { file_google_protobuf_empty, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt"

/**
 * Describes the file identity.proto.
 */
export const file_identity: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Cg5pZGVudGl0eS5wcm90bxINZ29raXQuYXV0aC52MTJRCg9JZGVudGl0eVNlcnZpY2USPgoGV2hvQW1JEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlYgZwcm90bzM",
    [file_google_protobuf_empty, file_google_protobuf_wrappers],
  )

/**
 * Minimal mirror of the gokit auth-host Connect contract: WhoAmI maps an empty
 * request to the authenticated principal string (for example "user:fixture-user").
 *
 * @generated from service gokit.auth.v1.IdentityService
 */
export const IdentityService: GenService<{
  /**
   * @generated from rpc gokit.auth.v1.IdentityService.WhoAmI
   */
  whoAmI: {
    methodKind: "unary"
    input: typeof EmptySchema
    output: typeof StringValueSchema
  }
}> = /*@__PURE__*/ serviceDesc(file_identity, 0)
