"use client"

// Generated by `bun run --filter @plainworks/ui codegen` — do not edit by hand. A
// tree-shakeable re-export of one @plainworks/elements atom, so a consumer can pull the atom
// and ui's composites from one package. The dependency direction (ui → elements) and the
// atom's provenance live in the elements registry.
export * from "@plainworks/elements/input"
