import { preset } from "@plainworks/tsdown-config"

// Generated by `bun run --filter @plainworks/ui codegen` — do not edit the entry map by hand.
// Each concern is its own entry so consumers tree-shake to what they import; the neutral
// `index` entry stays free of the client graph.
export default preset({
  entry: {
    index: "src/index.ts",
    client: "src/client.ts",
    hooks: "src/client/hooks/index.ts",
    layout: "src/client/layout/index.ts",
    feedback: "src/client/feedback/index.ts",
    overlays: "src/client/overlays/index.ts",
    display: "src/client/display/index.ts",
    navigation: "src/client/navigation/index.ts",
    "data-table": "src/client/data-table/index.ts",
    forms: "src/client/forms/index.ts",
    list: "src/client/list/index.ts",
    page: "src/client/page/index.ts",
    "theme-client": "src/client/theme/index.ts",
  },
  // tsdown has no CSS pipeline, so the Tailwind-source stylesheet is copied verbatim into
  // `dist`; the `./styles.css` export resolves from the build output the packaging gate covers.
  copy: [{ from: "src/styles.css", to: "dist" }],
})
