import { type PackageBuild, preset } from "@plainworks/tsdown-config"

// Generated by `bun run --filter @plainworks/ui codegen` — do not edit the entry map by hand.
// Each component is its own `<concern>/<module>` entry, so an import loads only that component;
// the neutral `index` entry stays free of the client graph.
export const build: PackageBuild = {
  entry: {
    index: "src/index.ts",
    "hooks/use-controllable-state": "src/hooks/use-controllable-state.ts",
    "hooks/use-disclosure": "src/hooks/use-disclosure.ts",
    "hooks/use-list-state": "src/hooks/use-list-state.ts",
    "hooks/use-selection": "src/hooks/use-selection.ts",
    "hooks/use-clipboard": "src/client/hooks/use-clipboard.ts",
    "hooks/use-keyboard-shortcuts": "src/client/hooks/use-keyboard-shortcuts.ts",
    "hooks/use-media-query": "src/client/hooks/use-media-query.ts",
    "layout/stack": "src/client/layout/stack.tsx",
    "layout/grid": "src/client/layout/grid.tsx",
    "layout/split": "src/client/layout/split.tsx",
    "layout/page": "src/client/layout/page.tsx",
    "layout/page-header": "src/client/layout/page-header.tsx",
    "layout/section": "src/client/layout/section.tsx",
    "layout/toolbar": "src/client/layout/toolbar.tsx",
    "feedback/async-state": "src/client/feedback/async-state.tsx",
    "feedback/callout": "src/client/feedback/callout.tsx",
    "feedback/empty-state": "src/client/feedback/empty-state.tsx",
    "feedback/error-state": "src/client/feedback/error-state.tsx",
    "feedback/loading-state": "src/client/feedback/loading-state.tsx",
    "feedback/spinner": "src/client/feedback/spinner.tsx",
    "overlays/drawer": "src/client/overlays/drawer.tsx",
    "overlays/modal": "src/client/overlays/modal.tsx",
    "display/date-value": "src/client/display/date-value.tsx",
    "display/number-value": "src/client/display/number-value.tsx",
    "display/status-badge": "src/client/display/status-badge.tsx",
    "navigation/breadcrumbs": "src/client/navigation/breadcrumbs.tsx",
    "navigation/nav-list": "src/client/navigation/nav-list.tsx",
    "theme/theme-mode-group": "src/client/theme/theme-mode-group.tsx",
    "theme/theme-mode-menu": "src/client/theme/theme-mode-menu.tsx",
    "theme/theme-mode-options": "src/client/theme/theme-mode-options.ts",
    "forms/form": "src/client/forms/form.tsx",
    "forms/form-context": "src/client/forms/form-context.ts",
    "forms/form-data": "src/client/forms/form-data.ts",
    "forms/form-submit": "src/client/forms/form-submit.tsx",
    "forms/field": "src/client/forms/field.tsx",
    "forms/text-field": "src/client/forms/text-field.tsx",
    "forms/number-field": "src/client/forms/number-field.tsx",
    "forms/date-field": "src/client/forms/date-field.tsx",
    "forms/textarea-field": "src/client/forms/textarea-field.tsx",
    "forms/select-field": "src/client/forms/select-field.tsx",
    "forms/checkbox-field": "src/client/forms/checkbox-field.tsx",
    "forms/switch-field": "src/client/forms/switch-field.tsx",
    "shell/app-shell": "src/client/shell/app-shell.tsx",
    "data/data-table": "src/client/data/data-table/index.ts",
    "data/filter-bar": "src/client/data/filter-bar.tsx",
    "data/filter-model": "src/client/data/filter-model.ts",
    "data/pagination": "src/client/data/pagination.tsx",
    "data/pagination-range": "src/client/data/pagination-range.ts",
  },
  // A DOM-only package: its client components render into the browser DOM.
  dom: true,
  // tsdown has no CSS pipeline, so the Tailwind-source stylesheet is copied verbatim.
  assets: { "styles.css": { from: "src/styles.css" } },
  // The shadcn registry points at authored `src` files, so it ships beside them.
  files: ["registry.json"],
}

export default preset(build)
