import { type PackageBuild, preset } from "@plainworks/tsdown-config"

// Generated by `bun run --filter @plainworks/ui codegen` — do not edit the entry map by hand.
// Each concern is its own entry so consumers tree-shake to what they import; the neutral
// `index` entry stays free of the client graph.
export const build: PackageBuild = {
  entry: {
    index: "src/index.ts",
    client: "src/client.ts",
    hooks: "src/client/hooks/index.ts",
    layout: "src/client/layout/index.ts",
    feedback: "src/client/feedback/index.ts",
    overlays: "src/client/overlays/index.ts",
    display: "src/client/display/index.ts",
    navigation: "src/client/navigation/index.ts",
    "data-table": "src/client/data-table/index.ts",
    forms: "src/client/forms/index.ts",
    list: "src/client/list/index.ts",
    page: "src/client/page/index.ts",
    shell: "src/client/shell/index.ts",
    theme: "src/client/theme/index.ts",
  },
  // tsdown has no CSS pipeline, so the Tailwind-source stylesheet is copied verbatim.
  assets: { "styles.css": { from: "src/styles.css" } },
  // The shadcn registry points at authored `src` files, so it ships beside them.
  files: ["registry.json"],
}

export default preset(build)
