import { execFileSync } from "node:child_process"
import { createHash } from "node:crypto"
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const revision = "579b386b92a364f5fa638757e67ae5980a26f138"
const source = process.argv.find((arg) => arg.startsWith("--source="))?.slice(9)
if (source === undefined) throw new Error("Pass --source=<gokit checkout>.")
const paths = {
  protocol: "sse/testdata/protocol.json",
  convergence: "sse/testdata/convergence.json",
  lists: "database/query/testdata/lists.json",
}
const fixtures = Object.entries(paths).map(([name, path]) => {
  const bytes = execFileSync("git", ["-C", source, "show", `${revision}:${path}`], {
    encoding: "utf8",
    timeout: 30_000,
  })
  return {
    name,
    path,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    data: JSON.parse(bytes),
  }
})
const output = `// Generated by scripts/sync-live.ts. Do not edit.\nexport const liveSource = ${JSON.stringify({ repository: "kbukum/gokit", revision, files: fixtures.map(({ name: _name, data: _data, ...file }) => file) })} as const\n${fixtures.map(({ name, data }) => `export const ${name}Fixture = ${JSON.stringify(data, null, 2)} as const`).join("\n")}\n`
const target = new URL("../src/stream/gen/fixtures.ts", import.meta.url)
const formatted = execFileSync(
  "bunx",
  ["--no-install", "biome", "format", "--stdin-file-path", fileURLToPath(target)],
  { input: output, encoding: "utf8", timeout: 30_000 },
)
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== formatted) throw new Error("Live fixture drift.")
} else {
  mkdirSync(new URL(".", target), { recursive: true })
  writeFileSync(target, formatted)
}
