import { execFileSync } from "node:child_process"
import { createHash } from "node:crypto"
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const revision = "579b386b92a364f5fa638757e67ae5980a26f138"
const directory = "contracttest/wire/testdata/wire"
const source = process.argv.find((arg) => arg.startsWith("--source="))?.slice(9)
if (source === undefined) throw new Error("Pass --source=<gokit checkout>.")
const git = (...args: string[]): string =>
  execFileSync("git", ["-C", source, ...args], { encoding: "utf8", timeout: 30_000 })
const files = git("ls-tree", "--name-only", `${revision}:${directory}`).trim().split("\n").sort()
const fixtures = files.map((file) => {
  const bytes = git("show", `${revision}:${directory}/${file}`)
  return {
    file,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    wire: JSON.parse(bytes),
  }
})
const output = `// Generated by scripts/sync-failures.ts. Do not edit.\nexport const failureSource = ${JSON.stringify({ repository: "kbukum/gokit", revision })} as const\nexport const wireFailures = ${JSON.stringify(fixtures, null, 2)} as const\n`
const target = new URL("../src/failure/gen/fixtures.ts", import.meta.url)
const formatted = execFileSync(
  "bunx",
  ["--no-install", "biome", "format", "--stdin-file-path", fileURLToPath(target)],
  { input: output, encoding: "utf8", timeout: 30_000 },
)
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== formatted) throw new Error("Failure fixture drift.")
} else {
  mkdirSync(new URL(".", target), { recursive: true })
  writeFileSync(target, formatted)
}
