// Public `./playwright` entry for `@plainworks/testkit`: the shared gate every reference
// host drives, the checks it runs, the flow engine, change review, and `ui:capture`. Re-export-only
// barrel. It runs in the Playwright test runner, so its peers (`@playwright/test`,
// `@axe-core/playwright`) are optional and only this subpath loads them.
export type {
  Allowance,
  AllowedFinding,
  AxeViolationSummary,
  BrowserAxeOptions,
  CheckId,
  Finding,
  FocusableFact,
  ImageFact,
  JudgedFindings,
  LayoutBox,
  LayoutFacts,
  RuntimeError,
  RuntimeErrorKind,
  RuntimeErrorWatch,
  TargetFact,
  TextFact,
  TrackedBox,
} from "./checks"
export {
  applyAllowances,
  BROWSER_AXE_TAGS,
  CHECK_IDS,
  capFindingsPerCheck,
  expectNoPageAxeViolations,
  expectPageFocusVisible,
  expectPageHydrated,
  expectPageReflow,
  findFocusProblems,
  findOverlaysOutsideViewport,
  focusWithKeyboard,
  formatAxeViolations,
  horizontalOverflow,
  judgeBrokenImages,
  judgeClippedText,
  judgeLayout,
  judgeLayoutShift,
  judgeObscuredFocusables,
  judgeOverlappingTargets,
  measureLayoutFacts,
  pressWithKeyboard,
  scanBrowserAxe,
  settleAnimations,
  waitForHydration,
} from "./checks"
export type {
  ArtifactStore,
  ChangeReview,
  ChangeStatus,
  ChangeTotals,
  CheckpointChecks,
  CheckpointLocation,
  CheckpointReport,
  ContactSheets,
  DeviceContextOptions,
  DeviceId,
  DevicePlan,
  DeviceProfile,
  DeviceRunOptions,
  EvidenceLinks,
  EvidenceSnapshot,
  Flow,
  FlowActionContext,
  FlowCheckpoint,
  FlowDeviceReport,
  FlowErrorKind,
  FlowFixtures,
  FlowMode,
  FlowPlanOptions,
  FlowReport,
  FlowReportSummary,
  FlowRun,
  FlowRunMode,
  FlowRunWriter,
  FlowSelection,
  FlowSession,
  FlowStatus,
  FlowSuite,
  FlowSuiteOptions,
  FlowTimeouts,
  FrameChange,
  MatrixPresetName,
  MatrixSpec,
  MemoryArtifactStore,
  PageFlowSession,
  PageFlowSessionOptions,
  PageVariant,
  PlannedFlowRun,
  PreferenceEmulation,
  PreferenceId,
  ReportedError,
  RetentionPolicy,
  ReviewBase,
  RunFlowOptions,
  SelectedFlow,
  SetupFlowRunOptions,
  StoredRun,
  ThemeAxes,
  ThemeAxisSelection,
  ThemeRoot,
  VariantReport,
  ViewportSize,
  VisualCapture,
} from "./flow"
export {
  collectFlowRun,
  createPageFlowSession,
  DEFAULT_FLOW_TIMEOUTS,
  DEFAULT_MATRIX_PRESET,
  DEFAULT_RETENTION,
  DEVICE_IDS,
  DEVICE_PROFILES,
  defineFlow,
  defineThemeAxes,
  describeChangeTotals,
  deviceContextOptions,
  expandFlowMatrix,
  FLOW_ERROR_KINDS,
  FLOW_MODES,
  FLOW_REPORT_SCHEMA_VERSION,
  FLOW_RUN_ENV,
  FLOW_SUITE_ENV,
  FlowError,
  flowArtifactPaths,
  flowOutcomeError,
  MATRIX_PRESETS,
  MODE_ONLY_THEME_AXES,
  memoryArtifactStore,
  nodeArtifactStore,
  openFlowRun,
  PREFERENCE_IDS,
  PREFERENCES,
  pageVariant,
  parseFlowDeviceReport,
  parseFlowReport,
  planFlowRuns,
  planFlowSuite,
  planRunRetention,
  publishFlowRun,
  renderFlowReportMarkdown,
  runFlow,
  runFlowOnDevice,
  samplePairwise,
  setupFlowRun,
  startFlowRun,
  summarizeFlowRuns,
} from "./flow"
export type {
  BrowserGateFixtures,
  BrowserGateOptions,
  BrowserGateStorageState,
  BrowserGateTest,
  BrowserGateWorkerFixtures,
} from "./gate"
export {
  BROWSER_GATE_NOW,
  browserGateUse,
  createBrowserGate,
  FIXED_NOW_ENV,
  GATE_ORIGIN_ENV,
} from "./gate"
export type { BrowserGateHost } from "./host"
export type {
  AriaDiff,
  AriaDiffOptions,
  ContactSheetOptions,
  FrameDiff,
  FrameDiffOptions,
  ReviewChangesOptions,
  ReviewedRun,
  SheetRenderer,
  SheetTarget,
} from "./review"
export { diffAriaSnapshots, diffFrames, reviewChanges, writeContactSheets } from "./review"
export type {
  AffectedFlows,
  AffectedFlowsOptions,
  BaseCapture,
  BaseUse,
  DocsImage,
  GitRunner,
  PlaywrightMcpConfig,
  PlaywrightMcpOptions,
  PublishedDocsImages,
  SuiteInvocation,
  UiCaptureArgs,
  UiCaptureConfig,
  UiCaptureErrorKind,
  UiCaptureRuntime,
  UiCaptureSelect,
} from "./ui-capture"
export {
  baseCacheKey,
  changedFilesSince,
  compileGlob,
  createNodeUiCaptureRuntime,
  DEFAULT_KEPT_BASES,
  docsImagesOf,
  evictBases,
  mergeBaseWith,
  nodeGitRunner,
  parseUiCaptureArgs,
  planBaseEviction,
  playwrightMcpConfig,
  playwrightMcpInitPage,
  publishDocsImages,
  readStoredReport,
  recordBaseUse,
  runUiCapture,
  runUiCaptureCli,
  saveSnapshot,
  selectAffectedFlows,
  UI_CAPTURE_EXIT,
  UI_CAPTURE_USAGE,
  UiCaptureError,
  uiCapturePaths,
} from "./ui-capture"
